import { type CSSProperties, type ReactNode } from "react";
import { AlertTriangle, ArrowLeft, Bookmark, CalendarDays, Check, CheckCircle2, ChevronLeft, ChevronRight, CircleDollarSign, ClipboardCheck, Clock3, Copy, Download, Heart, Info, Lightbulb, ListChecks, Map as MapIcon, MapPinned, Menu, Navigation, Share2, Ticket, Upload, X, type LucideIcon } from "lucide-react";
import { BottomSheet, KeyboardTextarea, useKeyboard } from "../mobile";
import type { Category, Place, TripDay, TransferMode, TransferStatus, TripGuideItem, TripGuideKind, View } from "./types";

const reservationLabels = { required: "예약 필수", recommended: "예약 권장", check_required: "확인 필요", completed: "예약 완료" } as const;

export type CategoryConfig = { key: Category; label: string; color: string; Icon: LucideIcon };

export function TravelHeader({ title, dateLabel, days, activeDay, view, menuOpen, onMenuToggle, onViewChange, onDayChange, onOpenGuide, onExportData, onImportData }: { title: string; dateLabel: string; days: TripDay[]; activeDay: TripDay; view: View; menuOpen: boolean; onMenuToggle: (open: boolean) => void; onViewChange: (view: View) => void; onDayChange: (day: number) => void; onOpenGuide?: () => void; onExportData: () => void; onImportData: () => void }) {
  const activeDayIndex = days.findIndex((day) => day.dayOfMonth === activeDay.dayOfMonth);
  const previousDay = activeDayIndex > 0 ? days[activeDayIndex - 1] : undefined;
  const nextDay = activeDayIndex >= 0 && activeDayIndex < days.length - 1 ? days[activeDayIndex + 1] : undefined;
  const dayNavigation = view === "schedule" ? <div className="header-day-nav" role="group" aria-label={`현재 DAY ${activeDay.dayNumber} ${activeDay.dayOfMonth}일`}><button type="button" onClick={() => previousDay && onDayChange(previousDay.dayOfMonth)} disabled={!previousDay} aria-label="이전 날짜"><ChevronLeft size={14} /></button><span className="header-day-label">DAY {activeDay.dayNumber} · {activeDay.dayOfMonth}일</span><button type="button" onClick={() => nextDay && onDayChange(nextDay.dayOfMonth)} disabled={!nextDay} aria-label="다음 날짜"><ChevronRight size={14} /></button></div> : null;
  return <header className="trip-header"><button type="button" className="icon-button header-back" aria-label={view === "schedule" ? "일정 홈" : "일정으로 돌아가기"} onClick={() => onViewChange("schedule")}><ArrowLeft size={22} strokeWidth={1.8} /></button><div className="header-copy"><strong>{title}</strong><div className="header-meta"><span>{dateLabel}</span>{dayNavigation}</div></div><button type="button" className="icon-button header-menu-button" aria-label="빠른 메뉴" aria-expanded={menuOpen} onClick={() => onMenuToggle(!menuOpen)}>{menuOpen ? <X size={21} strokeWidth={1.8} /> : <Menu size={22} strokeWidth={1.8} />}</button>{menuOpen ? <div className="quick-menu" role="menu"><button type="button" role="menuitem" onClick={() => { onViewChange("schedule"); onMenuToggle(false); }}><CalendarDays size={16} /> 오늘 일정</button><button type="button" role="menuitem" onClick={() => { onViewChange("map"); onMenuToggle(false); }}><MapIcon size={16} /> 전체 지도</button><button type="button" role="menuitem" onClick={() => { onViewChange("reservations"); onMenuToggle(false); }}><Bookmark size={16} /> 예약 확인</button>{onOpenGuide ? <button type="button" role="menuitem" onClick={() => { onOpenGuide(); onMenuToggle(false); }}><ListChecks size={16} /> 준비·꿀팁</button> : null}<span className="quick-menu-divider" aria-hidden="true" /><button type="button" role="menuitem" onClick={onExportData}><Download size={16} /> 데이터 내보내기</button><button type="button" role="menuitem" onClick={onImportData}><Upload size={16} /> 데이터 가져오기</button></div> : null}</header>;
}

export function TravelBottomNav({ view, onViewChange }: { view: View; onViewChange: (view: View) => void }) {
  const items: Array<{ key: View; label: string; Icon: LucideIcon }> = [{ key: "schedule", label: "일정", Icon: CalendarDays }, { key: "map", label: "지도", Icon: MapIcon }, { key: "reservations", label: "예약", Icon: Bookmark }, { key: "saved", label: "저장", Icon: Heart }];
  return <nav className="trip-bottom-nav" aria-label="주요 메뉴">{items.map(({ key, label, Icon }) => <button type="button" key={key} className={view === key ? "is-active" : ""} onClick={() => onViewChange(key)} aria-current={view === key ? "page" : undefined}><Icon size={20} fill={key === "saved" && view === key ? "currentColor" : "none"} /><span>{label}</span></button>)}</nav>;
}

export function TravelCategoryLegend({ categories }: { categories: CategoryConfig[] }) {
  return <div className="category-legend" aria-label="번호 원형 색상 기준">{categories.map(({ key, label, color }) => <span key={key}><i style={{ backgroundColor: color }} />{label}</span>)}</div>;
}

const guideGroupConfig: Array<{ key: TripGuideKind; label: string; Icon: LucideIcon }> = [
  { key: "must", label: "필수 준비", Icon: ClipboardCheck },
  { key: "warning", label: "주의할 점", Icon: AlertTriangle },
  { key: "tip", label: "여행 꿀팁", Icon: Lightbulb },
];

export function TravelGuideSheet({ open, items, completedIds, onClose, onToggle }: { open: boolean; items: TripGuideItem[]; completedIds: string[]; onClose: () => void; onToggle: (id: string) => void }) {
  const checkableItems = items.filter((item) => item.checkable !== false);
  const completedCount = checkableItems.filter((item) => completedIds.includes(item.id)).length;
  return <BottomSheet open={open} onOpenChange={(nextOpen) => { if (!nextOpen) onClose(); }} title="준비·꿀팁" description="예약·입장·이동 전에 확인할 내용을 모아두었어요." snap={0.9}><div className="guide-sheet-content"><div className="guide-summary"><div><ListChecks size={18} /><span>준비 체크리스트</span></div><strong>{completedCount}/{checkableItems.length} 완료</strong></div>{items.length ? guideGroupConfig.map(({ key, label, Icon }) => { const groupItems = items.filter((item) => item.kind === key); if (!groupItems.length) return null; return <section className={`guide-group guide-${key}`} key={key} aria-labelledby={`guide-heading-${key}`}><div className="guide-group-heading"><Icon size={17} /><h3 id={`guide-heading-${key}`}>{label}</h3><span>{groupItems.length}</span></div><div className="guide-list">{groupItems.map((item) => { const checked = completedIds.includes(item.id); return <article className={`guide-item${checked ? " is-completed" : ""}`} key={item.id}>{item.checkable === false ? <span className="guide-item-icon"><CheckCircle2 size={17} /></span> : <button type="button" className="guide-check" onClick={() => onToggle(item.id)} aria-label={`${item.title} ${checked ? "완료 해제" : "완료 처리"}`} aria-pressed={checked}>{checked ? <Check size={15} /> : null}</button>}<div className="guide-item-copy"><strong>{item.title}</strong>{item.dayNumber ? <span className="guide-day-label">DAY {item.dayNumber}</span> : null}<p>{item.body}</p>{item.sourceUrls?.length ? <div className="guide-sources">{item.sourceUrls.map((sourceUrl, index) => <a href={sourceUrl} target="_blank" rel="noreferrer" key={sourceUrl}>출처{item.sourceUrls!.length > 1 ? ` ${index + 1}` : ""}</a>)}</div> : null}</div></article>;})}</div></section>;}) : <div className="guide-empty"><Lightbulb size={22} /><strong>아직 준비 정보가 없어요</strong><p>여행 조사 단계에서 필수 준비사항과 꿀팁을 추가해 주세요.</p></div>}</div></BottomSheet>;
}

export function TravelPlaceCard({ place, selected, completed, favorite, category, closureText, preview, onSelect, onToggleComplete, onToggleFavorite }: { place: Place; selected: boolean; completed: boolean; favorite: boolean; category: CategoryConfig; closureText?: string; preview: ReactNode; onSelect: () => void; onToggleComplete: () => void; onToggleFavorite: () => void }) {
  const { Icon } = category;
  const reservationStatus = place.reservationStatus && place.reservationStatus !== "not_required" ? place.reservationStatus : undefined;
  return <article id={`place-${place.id}`} className={`place-card category-${place.category}${selected ? " is-selected" : ""}${completed ? " is-completed" : ""}${place.optional ? " is-optional" : ""}`}><button type="button" className="place-main" onClick={onSelect} aria-label={`${place.order}번 ${place.name} 상세 보기`}><span className="place-number" style={{ "--number-color": category.color } as CSSProperties} title={category.label}>{place.order}</span><span className="place-copy"><span className="place-title-row"><strong>{place.name}</strong>{place.optional ? <span className="optional-tag">대체</span> : null}</span><span className="place-meta"><span className={`category-icon category-${place.category}`}><Icon size={14} /></span><span>{category.label}</span>{place.plannedTime ? ` · ${place.plannedTime}` : ""}</span>{reservationStatus ? <span className={`reservation-badge status-${completed ? "completed" : reservationStatus}`}>{completed ? reservationLabels.completed : reservationLabels[reservationStatus]}</span> : null}{place.optional && place.nearbyWalk ? <span className="nearby-label"><MapPinned size={13} /> {place.nearbyWalk}</span> : null}{place.hours || place.price || place.admission ? <span className="place-facts">{place.hours ? <span><Clock3 size={12} /> {place.hours}</span> : null}{place.price ? <span><CircleDollarSign size={12} /> {place.price}</span> : null}{place.admission ? <span><Ticket size={12} /> {place.admission}</span> : null}</span> : null}{closureText ? <span className={`place-closed-days${closureText === "확인 필요" ? " is-warning" : ""}`}><CalendarDays size={12} /><span>휴무일 · {closureText}</span></span> : null}{place.notes ? <span className="place-note">{place.notes}</span> : null}{typeof place.latitude !== "number" || typeof place.longitude !== "number" ? <span className="location-warning"><Info size={13} /> 지도 위치 확인 필요</span> : null}<span className="place-actions"><a href={place.googleMapsUrl} target="_blank" rel="noreferrer" onClick={(event) => event.stopPropagation()}><MapIcon size={14} /> 지도</a>{place.directionsUrl ? <a href={place.directionsUrl} target="_blank" rel="noreferrer" onClick={(event) => event.stopPropagation()}><Navigation size={14} /> 길찾기</a> : null}</span></span>{preview}</button><div className="place-card-controls"><button type="button" className={`favorite-button${favorite ? " is-active" : ""}`} onClick={onToggleFavorite} aria-label={favorite ? `${place.name} 즐겨찾기 해제` : `${place.name} 즐겨찾기`} aria-pressed={favorite}><Heart size={17} fill={favorite ? "currentColor" : "none"} /></button><button type="button" className={`complete-button${completed ? " is-active" : ""}`} onClick={onToggleComplete} aria-label={completed ? `${place.name} 완료 해제` : `${place.name} 방문 완료`} aria-pressed={completed}>{completed ? <Check size={16} /> : <span />}<span>{completed ? "완료" : "체크"}</span></button></div></article>;
}

export function TravelDataTransferSheet({ open, mode, text, status, onClose, onTextChange, onImport, onCopy, onShare, onDownload, onFileSelect }: { open: boolean; mode: TransferMode; text: string; status: TransferStatus; onClose: () => void; onTextChange: (value: string) => void; onImport: () => void; onCopy: () => void; onShare: () => void; onDownload: () => void; onFileSelect: (file: File) => void }) {
  const keyboard = useKeyboard();
  const exporting = mode === "export";
  return <BottomSheet open={open} onOpenChange={(nextOpen) => { if (!nextOpen) onClose(); }} title={exporting ? "여행 데이터 내보내기" : "여행 데이터 가져오기"} description={exporting ? "현지 기록을 카카오톡이나 AI에게 공유해 두세요." : "저장해 둔 여행 데이터를 이 기기에 업데이트하세요."} snap={0.9}><div className="transfer-sheet-content"><div className="transfer-help"><Info size={16} /><span>{exporting ? "아래 JSON을 복사해 카카오톡 나에게 보내기, 메모장, 또는 AI 채팅에 저장할 수 있어요. 나중에 이 앱에서 그대로 가져오면 방문 체크·메모·수정 내용을 복원합니다." : "카카오톡이나 파일에서 받은 JSON 전체를 붙여넣으세요. 같은 여행 데이터인지 확인한 뒤 현재 기기의 기록을 교체합니다."}</span></div><KeyboardTextarea className="transfer-textarea" value={text} onChange={(event) => onTextChange(event.target.value)} onBlur={() => keyboard.hide()} placeholder={exporting ? "여행 데이터가 여기에 표시됩니다." : "여기에 JSON 전체를 붙여넣으세요."} rows={exporting ? 12 : 10} readOnly={exporting} spellCheck={false} />{status ? <p className={`transfer-status is-${status.tone}`} role={status.tone === "error" ? "alert" : "status"}>{status.message}</p> : null}{exporting ? <div className="transfer-actions"><button type="button" className="transfer-primary-button" onClick={onShare}><Share2 size={16} /> 카톡·앱으로 공유</button><button type="button" className="transfer-secondary-button" onClick={onCopy}><Copy size={16} /> 텍스트 복사</button><button type="button" className="transfer-secondary-button" onClick={onDownload}><Download size={16} /> 파일로 저장</button><button type="button" className="transfer-secondary-button" onClick={onClose}>닫기</button></div> : <div className="transfer-actions"><label className="transfer-secondary-button transfer-file-button"><Upload size={16} /> 파일 선택<input type="file" accept=".json,application/json" onChange={(event) => { const file = event.target.files?.[0]; event.target.value = ""; if (file) onFileSelect(file); }} /></label><button type="button" className="transfer-primary-button" onClick={onImport} disabled={!text.trim()}><Upload size={16} /> 이 데이터로 업데이트</button><button type="button" className="transfer-secondary-button" onClick={onClose}>취소</button></div>}</div></BottomSheet>;
}
